#format can be "text" or "json" for different output (human or machine readable)
#format: "text"
#checkAsserts checks assertions
checkAsserts: true
#testLimit is the number of test sequences to run
testLimit: 1000000
#seqLen defines how many transactions are in a test sequence
seqLen: 200
#solcArgs allows special args to solc
solcArgs: "--optimize --optimize-runs 200"
#cryticArgs allows special args to crytic
cryticArgs: ["--solc-solcs-select", "0.6.12"]
#maximum time between generated txs; default is one week
maxTimeDelay: 15778800 # approximately 6 months
#directory to save the corpus; by default is disabled
corpusDir: "corpus"
#deployer is address of the contract deployer (who often is privileged owner, etc.)
deployer: "0x41414141"
#sender is set of addresses transactions may originate from
sender: ["0x42424242", "0x43434343"]
